import Layout from "./Layout";

const Artista = () => {
    return (
    <>
    <h1 className="tituloArtista">Artistas</h1>
    <div>
      <p>Nessa págimas, listamos 5 dos cantores mais conhecidos mundialmente.</p>
      <p className="cantor">Bob Marley</p>
        <p>Breve Descrição:</p>
        <p>Robert Nesta Marley (Nine Mile, 6 de fevereiro de 1945 – Miami, 11 de maio de 1981) foi um cantor e compositor jamaicano, o mais conhecido músico de reggae de todos os tempos, famoso por popularizar internacionalmente o gênero. Já vendeu mais de 75 milhões de discos e, em 1978, três anos antes de sua morte, foi condecorado pela ONU com a "Medalha da Paz do Terceiro Mundo". Sua obra tratava principalmente de temas político-sociais e espirituais. Dedicado a protestar contra injustiças sociais, Bob Marley é mundialmente celebrado como a voz dos pobres e oprimidos, sendo considerado um símbolo de resistência negra, espiritualidade, defesa dos direitos humanos e luta por justiça social. Suas músicas denunciavam o racismo, a desigualdade social, o colonialismo e a guerra. Devoto do movimento religioso rastafári, a vida e a obra de Bob Marley foram profundamente influenciadas por sua fé. Sua música serviu de porta-voz às convicções e temas da fé rastafári, como as interpretações afrocêntricas da Bíblia e o pan-africanismo. A África e suas questões, como a miséria e a colonização europeia, foram também assuntos amplamente abordados em suas músicas.</p>
      <p className="cantor">Whitney Houston</p>
        <p>Breve Descrição:</p>
        <p>Whitney Elizabeth Houston (Newark, 9 de agosto de 1963 — Beverly Hills, 11 de fevereiro de 2012) foi uma premiada cantora, compositora, atriz, produtora, supermodelo e empresária norte-americana. É considerada por alguns críticos como a melhor cantora de todos os tempos. Seus poderosos vocais, que alcançavam extensões muito altas, principalmente nos melismas e vibratos, aliados às tessituras suaves, e seu extremo talento artístico na composição de letras e melodias, fizeram-na ser conhecida como A Voz e Rainha da Balada. Houston foi a artista mais premiada de todos os tempos, de acordo com o Guinness World Records, em 2009. Sua lista de prêmios inclui: dois Emmy Awards, sete Grammy Awards; dezesseis Billboard Music Awards, vinte e dois American Music Awards, num total de 415 prêmios conquistados em sua carreira até 2013. Uma das artistas mais bem sucedidas do mundo da música, vendeu mais de 400 milhões de discos em todo o mundo. Inspirada por vários cantores de soul de destaque em sua família, incluindo a mãe, Cissy Houston, as primas Dionne Warwick e Dee Dee Warwick, Houston começou a cantar com o coral gospel júnior da Igreja de Nova Jersey aos 11 anos de idade. Depois que ela começou a trabalhar como backing vocal nos shows de sua mãe em boates de Nova York, em 1977, ela foi descoberta por Clive Davis em 1983, ano de início de sua carreira profissional. Ele era empresário da Arista Records. Houston lançou seis álbuns de estúdio e três álbuns de trilha sonora, todos eles certificados com diamante, multiplatina, platina e ouro pela Recording Industry Association of America. Seu álbum de estreia autointitulado, lançado em 1985, se tornou o álbum de estreia mais vendido por uma artista feminina, com 25 milhões de cópias vendidas. Seu segundo álbum, Whitney (1987), tornou-se o primeiro álbum de uma artista feminina a estrear em primeiro lugar na Billboard 200. Whitney alcançou grandes sucessos nas paradas de música popular, bem como sua proeminência na MTV, começando com seu vídeo de How Will I Know, permitiu várias artistas femininas afro-americanas seguirem seu sucesso.</p>
      <p className="cantor">Aretha Franklin</p>
        <p>Breve Descrição:</p>
        <p>Aretha Louise Franklin (Memphis, 25 de março de 1942 — Detroit, 16 de agosto de 2018) foi uma cantora e compositora norte-americana de gospel, R&B e soul que se tornou ícone da música negra. Foi considerada a "maior cantora de todos os tempos" pela revista Rolling Stone. E, pela mesma revista, a nona maior artista da música de todos os tempos. Sua voz foi declarada oficialmente “um recurso natural” pelo estado de Michigan. Apesar de todo o sucesso, Franklin teve apenas dois singles que foram para o primeiro lugar na Hot 100, segundo a revista Billboard: "Respect", na década de 1960 – sua canção mais conceituada – e "I Knew You Were Waiting (For Me)", um dueto com George Michael. No entanto, vários singles dela já apareceram entre os vinte mais vendidos na mesma tabela musical; como exemplos, pode-se citar "Think", "I Say A Little Prayer", "(You Make Me Feel Like) a Natural Woman", "Until You Come Back to Me (That's What I'm Gonna Do)", "Chain of Fools", "(Sweet, Sweet Baby) Since You've Been Gone", "Call Me", "Ain't No Way", "Don't Play That Song", "Freeway of Love", entre outros. Franklin também foi agraciada com inúmeras honrarias ao longo de sua carreira. É detentora da Medalha Nacional das Artes e também da Medalha Presidencial da Liberdade, a maior condecoração para um cívil norte-americano. Em 1987, tornou-se a primeira artista feminina a ser introduzida no Hall da Fama do Rock and Roll, e em 2019, de maneira póstuma, foi a primeira mulher a receber individualmente o Prêmio Pulitzer na categoria Citação Especial, "por sua contribuição para a música e para a cultura americana por mais de cinco décadas". É também uma das artistas recordistas de vendas, alcançando a marca de 75 milhões de discos vendidos em todo o mundo.</p>
      <p className="cantor">Mariah Carey</p>
        <p>Breve Descrição:</p>
        <p>Mariah Carey (Huntington, 27 de março de 1969) é uma cantora, compositora, produtora musical e atriz estadunidense. Reconhecida por seu alcance vocal de cinco oitavas, estilo de canto melismático e uso exclusivo do registro de apito, ela é referida como "Pássaro Supremo" e "Rainha do Natal". Ao longo de sua carreira, Carey tem sido considerada uma das maiores e mais influentes vocalistas da história da música gravada. É creditada por ter influenciado a construção vocal de diversos artistas de diversos gêneros musicais e como uma das primeiras artistas a popularizar o hip hop e a prática dos remixes na música popular. Sob a orientação de seu ex-marido, o executivo Tommy Mottola, Carey alcançou fama no início da década de 1990, após assinar com a Sony Music e liberar seu álbum de estreia homônimo, que liderou a Billboard 200 por onze semanas seguidas. O trabalho fez dela o único artista na história a ter seus cinco primeiros singles — de "Vision of Love" a "Emotions" —, em primeiro lugar na Billboard Hot 100. Sua popularidade atingiu o ápice com seus discos subsequentes Music Box (1993) e Daydream (1995), que venderam mais de 20 milhões de cópias mundialmente e foram certificados de diamante nos Estados Unidos. Com esse último projeto, Carey fez história quando o single, "One Sweet Day", um dueto com Boyz II Men, esteve por 16 semanas consecutivas na liderança da Billboard Hot 100, um recorde mantido por 23 anos. Em paralelo, ela liberou Merry Christmas (1994), que extraiu o single "All I Want for Christmas Is You". Ambos sagraram-se como o disco e a canção com temática natalina mais comprados de todos os tempos. Depois de se separar de Mottola, Carey adotou uma nova imagem e incorporou mais elementos de hip hop em suas obras, o que ficou evidente com o lançamento de Butterfly (1997) e Rainbow (1999).</p>
      <p className="cantor">Jonh Legend</p>
        <p>Breve Descrição:</p>
        <p>John Roger Stephens (Springfield, 28 de dezembro de 1978), conhecido pelo nome artístico John Legend, é um cantor e compositor norte-americano, vencedor do Oscar de Melhor Canção Original pela canção Glory para o filme Selma. Ele colaborou com Slum Village na música "Selfish" (Top 100 nos EUA), música em que Kanye West também participa. Legend participou no CD Late Orchestration de Kanye West, tocando piano ao vivo em Londres. Também tocou piano em "Everything is Everything" de Lauryn Hill e fez backing vocal em "Encore" de Jay-z, "You Don't Know My Name" da Alicia Keys, "High Road" do Fort Minor. Em 2005, cantou o clássico With you I'm born again com Mariah Carey no especial Save The Music. Seu irmão Vaughn Anthony também é cantor. Legend criou a música "All of me" para dedicar à mulher. Cantou a canção tema do filme Bela e a fera.</p>
    </div>
    <Layout></Layout>
    </>
  )
  };
  
  export default Artista;